### ISSUE TITLE
Height and weight generators do not consider race and gender which creates 6ft tall dwarfs and 1ft tall orcs

### ISSUE THREAD

**Issue by Meepedy** [Meepedy/whoami#6]
I quickly put together the height and weight generators so right now height is just a random number between 0-7ft and weight is just 0-300lbs. So a 7ft 300lbs dwarf could be generated which isn't great even if it is slightly amusing to picture in my head.

It is currently some little math in charGen.js, maybe a function for genHeight and genWeight should be created to take in race and gender.

**Comment by ikad95** [comment]
My proposal is to make weight a function of height (let's generate a random BMI instead of weight). And about gender, we can find out the average male to female BMI ratio.

**Comment by Meepedy** [comment]
> My proposal is to make weight a function of height (let's generate a random BMI instead of weight). And about gender, we can find out the average male to female BMI ratio.

@ikad95 That...is a pretty good idea, I like it. Slight issue being that since the character generator is for table top rpg's  and allows for things like Orcs, finding the average BMI for Orcs might be tricky but really I bet someone has defined the average height and weight of Orcs.

**Comment by ikad95** [comment]
It seems so.
http://www.canonfire.com/cf//modules.php?name=Forums&file=viewtopic&t=5156
https://rstudio-pubs-static.s3.amazonaws.com/74993_079229a18ce141468a62ae01b5b475d5.html#/3

**Comment by Meepedy** [comment]
Could also just store the different races as objects and store what characteristics they can have in their properties so that it first randomly selects a race and then chooses from those characteristics. Because sometimes things like hair, face shape, age, body type, etc... might be specific to a certain race.
